### ISSUE TITLE
Looks like Google have potentially changed or retired the API

### ISSUE THREAD

**Issue by mooncresta** [rdiver/nest-php-api-hot-water#2]
Been working like a dream, but started doing this 2 days ago
[12-Nov-2019 09:00:26 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error during GET of '/v2/mobile/user.': ' in /home/XXXX/public_html/Nest/nest-php-api.php:117
Stack trace:
#0 /home/XXXX/public_html/Nest/nest-php-api.php(84): Nest->curlGet('/v2/mobile/user...')
#1 /home/XXXX/public_html/Nest/nest-php-api.php(63): Nest->getHotWaterStatus()
#2 /home/XXXX/public_html/Nest/example_boost_hot_water.php(18): Nest->setHotWaterBoost(60)
#3 {main}
  thrown in /home/XXXX/public_html/Nest/nest-php-api.php on line 117

Will look at adding some debugging later - or is it just me ?

**Comment by rdiver** [comment]
I had a look this morning and google have stuffed it. It appears that google has changed the login format and that has now broken the script. To make things worse, they have added a reCapcha that will be more difficult to bypass. I feel this might be the end, but will do some digging next week.

**Comment by chinswain** [comment]
I've just integrated my thermostat to Home Assistant, I had to convert my nest account to google and capture the token and cookie, should work for this project?

https://github.com/USA-RedDragon/badnest
https://github.com/chrisjshull/homebridge-nest/

**Comment by rdiver** [comment]
@chinswain you are a bloody legend!!!
Did some digging and found this. 

The following API has the hot water tools in there! It's actually pretty amazing. 
https://github.com/gboudreau/nest-api

To get it working with Nest login, just need to do the following.
https://gist.github.com/gboudreau/8b8851a9c99140b6234856bbc80a2d24
